export const AuditAction = {
  SUBMIT_CHAPTER: 'SUBMIT_CHAPTER',
  GENERATE_REVIEW: 'GENERATE_REVIEW',
  APPROVE_CHAPTER: 'APPROVE_CHAPTER',
  REJECT_CHAPTER: 'REJECT_CHAPTER',
  CREATE_USER: 'CREATE_USER',
  ASSIGN_TUTOR: 'ASSIGN_TUTOR',
  ADD_OBSERVATION: 'ADD_OBSERVATION',
  DELETE_OBSERVATION: 'DELETE_OBSERVATION',
  UPLOAD_KNOWLEDGE: 'UPLOAD_KNOWLEDGE',
  DELETE_KNOWLEDGE: 'DELETE_KNOWLEDGE',
  LOGIN: 'LOGIN',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
